### ISSUE TITLE
unable to find genes when export to SPRING object

### ISSUE THREAD

**Issue by MichaelPeibo** [AllonKleinLab/SPRING_dev#10]
Hi SPRING team,
I convert Seurat obj to anndata with:
`mda_ad <- Convert(from = mda, to = "anndata",filename = 'mda_day27_ad.h5ad')`

> 
> mda_ad
AnnData object with n_obs × n_vars = 6039 × 19331 
    obs: 'n_genes', 'n_counts', 'orig_ident', 'percent_mito', 'S_Score', 'G2M_Score', 'Phase', 'old_ident', 'res_1_2'
    var: 'gene.mean', 'gene.dispersion', 'gene.dispersion.scaled'
    obsm: 'X_pca', 'X_tsne'

Then I run as scanpy's tutorial https://github.com/theislab/scanpy_usage/blob/master/171111_SPRING_export/SPRING_export.ipynb
to export SPRING, however, I was unable to find no response when I enter a gene in the web browser. 
I have all required files in the folder.
![image](https://user-images.githubusercontent.com/32219336/54064912-58710a00-4254-11e9-8ee3-b4d13a43d786.png)
![image](https://user-images.githubusercontent.com/32219336/54064914-5eff8180-4254-11e9-8d57-f12bb8c56c08.png)

Any suggestion how to solve it?

Thanks!

![image](https://user-images.githubusercontent.com/32219336/54035115-8a9e4f80-41f3-11e9-998d-326df9fcf89a.png)

**Comment by calebweinreb** [comment]
Can you send the text from the console that came up as you tried to load
genes? Also can you send a directory containing all the data output by
scanpy so we can try to load it into SPRING?

**Comment by MichaelPeibo** [comment]
Hi @calebweinreb 
I went through it today.
I guess it may be due to the multiple web server error when I first start it?

Or maybe both my server and me need a rest and restart.....

Sorry to bother, very nice interactive tool!!!
