### ISSUE TITLE
cell barcodes IDs for download files

### ISSUE THREAD

**Issue by lb15** [AllonKleinLab/SPRING_dev#15]
Hi!

Great tool! For the various downloads (doublet scores, coordinates, etc), can I assume that the values are in the same cell order as the input matrix? Or is there a way to add the cell barcode IDs to the download? 

Thanks!

**Comment by calebweinreb** [comment]
Hi,

Yes you can assume this! The only reason it might differ is if cells were
filtered out during the analysis. If the number of cells output by SPRING
in these various files is equal to the number that you put in, then the
order is the same. There is no way to track cell barcodes.

**Comment by lb15** [comment]
I see, thanks!
