### ISSUE TITLE
Changing expression colors

### ISSUE THREAD

**Issue by justinesjw** [AllonKleinLab/SPRING_dev#24]
Hi SPRING_dev team! 

Thanks for the awesome tools! 

I may have missed this, can you please guide me to where can I change the expression colors?

Currently it's green in color. For better visualization, I want more tones to it maybe a viridis.
![image](https://user-images.githubusercontent.com/26448066/100704096-da697500-33df-11eb-8ad1-6780d306d099.png)

Thanks! 
Justine

**Comment by AllonKleinLab** [comment]
Hi Justine! We haven’t implemented that at the GUI level yet. If you wanted to edit the code, it should be straightforward. Copying in Caleb and Sam in case they can quickly give the answer.

On Dec 1, 2020, at 1:18 AM, justinesjw <notifications@github.com> wrote:

﻿

Hi SPRING_dev team!

Thanks for the awesome tools!

I may have missed this, can you please guide me to where can I change the expression colors?

Currently it's green in color. For better visualization, I want more tones to it maybe a viridis.
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_26448066_100704096-2Dda697500-2D33df-2D11eb-2D8ad1-2D6780d306d099.png&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=k8xAWGirsd-UdOwtVp-_wvT_xZ_77NGM4A6xjZIgrkc&m=Ac9e7nUjClvnTsQVNxaBaMYwNLBZAwebague1kSy1vw&s=Ath0iaQMkcWZbg0LeR2z-OVt4m8r995JP0BKZ9ovPfY&e=>

Thanks!
Justine

**Comment by calebweinreb** [comment]
Hi Justine,

We currently don't have the ability to swap in new colorscales. You could
edit the code to interpolate between black and some color other than green,
but using a colorscale like viridis would be more complicated. I think the
easiest way for you to proceed would be the following:

1) Download the SPRING coordinates using the Download menu
2) The coordinates file should have three columns, the second and third
columns are the x and y coordinates of each cell (note that y is usually
flipped so you will have to use -y). The first column contains the (base-0)
index of each cell with respect to the original expression matrix that you
uploaded.
3) If you load the coordinates into R, python, matlab or whatever software
you use, it should be possible to recreate the gene expression plot using
your original gene expression data. The only way that the SPRING plot
differs from the uploaded data is that the gene expression values are
total-counts normalized, so you may want to include this step prior to
plotting.
4) If you would like to included edges in the plot, the edges can also be
downloaded and plotted behind the points.

**Comment by justinesjw** [comment]
Noted with thanks!

Hope you guys are doing well :)
