### ISSUE TITLE
Problem about SPRING_py3  ./start_server.sh

### ISSUE THREAD

**Issue by Mcdull8** [AllonKleinLab/SPRING_dev#32]
Hi!

I followed the SPRING_py3 pipeline and created the environment, however when I started ./start_server.sh, the sever showed

Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

![image](https://github.com/AllonKleinLab/SPRING_dev/assets/121401059/a536c3a6-08d2-43f2-b482-1877ebfb09b7)

Do you have any suggestions as to what to do?

**Comment by calebweinreb** [comment]
What's shown in the terminal that you launched the server from?

**Comment by Mcdull8** [comment]
![image](https://github.com/AllonKleinLab/SPRING_dev/assets/121401059/55c2a45a-6c1b-42eb-af79-a3b158143f1e)
Here

**Comment by calebweinreb** [comment]
Seems like it's running on port 5000 whereas your URL is 8000

**Comment by Mcdull8** [comment]
Oh, sorry, I tried the 8000 again, but the result is the same
![image](https://github.com/AllonKleinLab/SPRING_dev/assets/121401059/5cc9c3bc-3ebe-408d-835d-c2c3d0966228)
![image](https://github.com/AllonKleinLab/SPRING_dev/assets/121401059/5850fd4c-a36a-47bc-8f9b-70e833f54bc7)

**Comment by Mcdull8** [comment]
I switched some ports and the results were all the same. /(ㄒoㄒ)/

**Comment by calebweinreb** [comment]
Hmm I'm actually not involved in the development of SPRING_py3. I don't see an option to post issues in the SPRING_py3 repo so you'll have to reach out to the developers directly I guess.

**Comment by Mcdull8** [comment]
OK thanks

**Comment by Mcdull8** [comment]
OK thanks
